// <auto-generated />
namespace Pristjek220Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Required_tag_added_to_Login : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Required_tag_added_to_Login));
        
        string IMigrationMetadata.Id
        {
            get { return "201604300926358_Required_tag_added_to_Login"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
